name: lint-commit-messages

on: [pull_request]

jobs:
  commitlint:
    runs-on: ktbs-infra-k8s-runner
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          helpURL: https://www.conventionalcommits.org/
